version: 2

jobs:
  specs:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
      - image: alphasights/rabbitmq:3.7
    steps:
      - checkout
      - run: bundle
      - run: bundle exec rake test

workflows:
  version: 2
  ci_workflow:
    jobs:
      - specs
